In [1]:
import torch
from tqdm import tqdm

# Import of clean dataloader

In [2]:
from data_utils.data_loaders import ClassifierDataLoader
dl = ClassifierDataLoader(
    images_dir="../../data/processed/COCO-2017/CocoPersonClassifier/train/images",
    batch_size=64,
    csv_path="../../data/processed/COCO-2017/CocoPersonClassifier/train/labels.csv",
    shuffle=True,
    validation_split=0.2,
    num_workers=8,
    balance=True,
)

# Function to calculate mean and std of the dataset

In [5]:
def get_mean_and_std(dataloader):
    channels_sum, channels_squared_sum, num_batches = 0, 0, 0
    for data, _ in tqdm(dataloader, desc="Calculating mean and std"):
        # Mean over batch, height and width, but not over the channels
        channels_sum += torch.mean(data, dim=[0,2,3])
        channels_squared_sum += torch.mean(data**2, dim=[0,2,3])
        num_batches += 1
    
    mean = channels_sum / num_batches

    # std = sqrt(E[X^2] - (E[X])^2)
    std = (channels_squared_sum / num_batches - mean ** 2) ** 0.5

    return mean, std

In [6]:
get_mean_and_std(dl)

Calculating mean and std: 100%|██████████| 1000/1000 [03:25<00:00,  4.86it/s]


(tensor([0.5462, 0.5803, 0.6043]), tensor([0.2952, 0.2886, 0.2965]))

# Check if works :) 

In [10]:
from data_utils.data_loaders import ClassifierDataLoader
dl2 = ClassifierDataLoader(
    images_dir="../../data/processed/COCO-2017/CocoPersonClassifier/train/images",
    batch_size=64,
    csv_path="../../data/processed/COCO-2017/CocoPersonClassifier/train/labels.csv",
    transform_mean=[0.5462, 0.5803, 0.6043],
    transform_std=[0.2952, 0.2886, 0.2965],
    shuffle=True,
    validation_split=0.2,
    num_workers=8,
    balance=True,
)

In [11]:
get_mean_and_std(dl2)

Calculating mean and std: 100%|██████████| 1000/1000 [04:17<00:00,  3.89it/s]


(tensor([ 5.6956e-05, -1.1733e-04, -1.3571e-04]),
 tensor([0.9999, 0.9999, 0.9999]))