In [5]:
%load_ext autoreload
%autoreload 2

import torch
from tqdm import tqdm

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Import of clean dataloader

In [6]:
from data_utils.data_loaders import ClassifierDataLoader
dl = ClassifierDataLoader(
    images_dir="../../data/processed/COCO-2017/CocoMultiClassifier/train/images",
    batch_size=64,
    csv_path="../../data/processed/COCO-2017/CocoMultiClassifier/train/labels.csv",
    shuffle=True,
    validation_split=0.0,
    num_workers=8,
    balance=True,
    is_multiclass = True
)

# Function to calculate mean and std of the dataset

In [7]:
def get_mean_and_std(dataloader):
    channels_sum, channels_squared_sum, num_batches = 0, 0, 0
    for data, _ in tqdm(dataloader, desc="Calculating mean and std"):
        # Mean over batch, height and width, but not over the channels
        channels_sum += torch.mean(data, dim=[0,2,3])
        channels_squared_sum += torch.mean(data**2, dim=[0,2,3])
        num_batches += 1
    
    mean = channels_sum / num_batches

    # std = sqrt(E[X^2] - (E[X])^2)
    std = (channels_squared_sum / num_batches - mean ** 2) ** 0.5

    return mean, std

In [8]:
get_mean_and_std(dl)

Calculating mean and std: 100%|██████████| 10511/10511 [36:21<00:00,  4.82it/s] 


(tensor([0.5438, 0.5786, 0.6030]), tensor([0.2944, 0.2882, 0.2966]))

# Check if works :) 

In [8]:
from data_utils.data_loaders import ClassifierDataLoader
dl2 = ClassifierDataLoader(
    images_dir="../../data/processed/COCO-2017/CocoCarClassifier/train/images",
    batch_size=64,
    csv_path="../../data/processed/COCO-2017/CocoCarClassifier/train/labels.csv",
    transform_mean=[0.5615,0.5820,0.5965],
    transform_std=[0.2911,0.2849,0.2908],
    shuffle=True,
    validation_split=0.0,
    num_workers=8,
    balance=True,
)

In [9]:
get_mean_and_std(dl2)

Calculating mean and std: 100%|██████████| 782/782 [02:41<00:00,  4.83it/s]


(tensor([ 3.9803e-05, -8.2328e-06, -1.3066e-04]),
 tensor([1.0000, 1.0001, 1.0000]))

# Results:
## Person:
+ "transform_mean": [0.5462,0.5803,0.6043]
+ "transform_std": [0.2952,0.2886,0.2965]
## Car:
+ "transform_mean": [0.5615,0.5820,0.5965]
+ "transform_std": [0.2911,0.2849,0.2908]
## Dog:
+ "transform_mean": [0.5243,0.5564,0.5869],
+ "transform_std": [0.2958,0.2923,0.3011]
## Bicycle:
+ "transform_mean": [0.5647,0.5906,0.6088]
+ "transform_std": [0.2894,0.283,0.2891]
## Cat:
+ "transform_mean": [0.5295,0.5672,0.5936]
+ "transform_std": [0.3045,0.3015,0.3107]
## Multi:
+ "transform_mean": [0.5438,0.5786,0.6030]
+ "transform_std": [0.2944,0.2882,0.2966]